"""change progress percentage type

Revision ID: 043e0a61f155
Revises: 233de3377cdf
Create Date: 2026-09-10 00:27:01.908721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043e0a61f155'
down_revision: Union[str, Sequence[str], None] = '233de3377cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress', 'progress_percentage',
               existing_type=sa.SMALLINT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progress', 'progress_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
