"""add organizational priority

Revision ID: 6e07e82fbfee
Revises: 9e55dcccd5d6
Create Date: 2026-09-07 23:45:22.641811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e07e82fbfee'
down_revision: Union[str, Sequence[str], None] = '9e55dcccd5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'role_competencies',
    sa.Column(
        'organizational_priority',
        sa.SmallInteger(),
        nullable=False,
        server_default=sa.text('1'),
    ),
)

    op.alter_column(
    'role_competencies',
    'organizational_priority',
    server_default=None,
)
    op.create_check_constraint('check_organizational_priority', 'role_competencies', 'organizational_priority BETWEEN 1 AND 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_organizational_priority', 'role_competencies', type_='check')
    op.drop_column('role_competencies', 'organizational_priority')
    # ### end Alembic commands ###
