"""Add tpac_requests table

Revision ID: c54712ac85cb
Revises: add_bloom_tag
Create Date: 2026-09-16 21:08:12.759292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54712ac85cb'
down_revision: Union[str, Sequence[str], None] = 'add_bloom_tag'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpac_requests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('cadre', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cadre')
    op.drop_table('tpac_requests')
    # ### end Alembic commands ###
