"""add ai generated questions

Revision ID: e6db1c02ccdf
Revises: 6e07e82fbfee
Create Date: 2026-09-09 00:12:13.043929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6db1c02ccdf'
down_revision: Union[str, Sequence[str], None] = '6e07e82fbfee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learning_content_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('beginner', 'intermediate', 'advanced')", name='check_ai_question_difficulty'),
    sa.CheckConstraint("question_type IN ('mcq')", name='check_ai_question_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_ai_question_status'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_content_id'], ['learning_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_generated_questions')
    # ### end Alembic commands ###
