import {
  EmployeeDashboardData,
  AdminDashboardData,
  StartAssessmentResponse,
  ScoreAssessmentResponse,
  AIGeneratedQuestionItem,
  LearningMaterial,
} from "./api";

export const MOCK_DASHBOARD: EmployeeDashboardData = {
  employee: {
    user_id: "user-ananya",
    email: "ananya.sharma@demo.gov.in",
    role_id: "role-statistical-officer",
    role_name: "Statistical Officer",
  },
  summary: {
    total_competencies: 18,
    competencies_with_gaps: 6,
    mastered_competencies: 12,
    total_recommendations: 8,
  },
  priority_gaps: [
    {
      competency_id: "comp-1",
      competency_name: "National Accounts",
      domain: "Domain",
      current_level: 2,
      current_level_label: "L2: Working Knowledge",
      required_level: 3,
      required_level_label: "L3: Practitioner",
      gap: 1,
      is_critical: true,
      organizational_priority: 5,
      priority_score: 7,
    },
    {
      competency_id: "comp-2",
      competency_name: "Survey Design",
      domain: "Statistical",
      current_level: 3,
      current_level_label: "L3: Practitioner",
      required_level: 4,
      required_level_label: "L4: Expert",
      gap: 1,
      is_critical: true,
      organizational_priority: 4,
      priority_score: 7,
    },
    {
      competency_id: "comp-3",
      competency_name: "Python for Statistics",
      domain: "Technical",
      current_level: 2,
      current_level_label: "L2: Working Knowledge",
      required_level: 3,
      required_level_label: "L3: Practitioner",
      gap: 1,
      is_critical: false,
      organizational_priority: 3,
      priority_score: 5,
    },
    {
      competency_id: "comp-4",
      competency_name: "Metadata Standards",
      domain: "Domain",
      current_level: 2,
      current_level_label: "L2: Working Knowledge",
      required_level: 3,
      required_level_label: "L3: Practitioner",
      gap: 1,
      is_critical: false,
      organizational_priority: 3,
      priority_score: 5,
    },
  ],
  competencies: [
    { competency_id: "comp-1", competency_name: "National Accounts", domain: "Domain", current_level: 2, current_level_label: "L2: Working Knowledge", required_level: 3, required_level_label: "L3: Practitioner", gap: 1, is_critical: true, organizational_priority: 5, priority_score: 7 },
    { competency_id: "comp-2", competency_name: "Survey Design", domain: "Statistical", current_level: 3, current_level_label: "L3: Practitioner", required_level: 4, required_level_label: "L4: Expert", gap: 1, is_critical: true, organizational_priority: 4, priority_score: 7 },
    { competency_id: "comp-3", competency_name: "Python for Statistics", domain: "Technical", current_level: 2, current_level_label: "L2: Working Knowledge", required_level: 3, required_level_label: "L3: Practitioner", gap: 1, is_critical: false, organizational_priority: 3, priority_score: 5 },
    { competency_id: "comp-4", competency_name: "Metadata Standards", domain: "Domain", current_level: 2, current_level_label: "L2: Working Knowledge", required_level: 3, required_level_label: "L3: Practitioner", gap: 1, is_critical: false, organizational_priority: 3, priority_score: 5 },
    { competency_id: "comp-5", competency_name: "SQL & Data Extraction", domain: "Technical", current_level: 3, current_level_label: "L3: Practitioner", required_level: 4, required_level_label: "L4: Expert", gap: 1, is_critical: false, organizational_priority: 3, priority_score: 5 },
    { competency_id: "comp-6", competency_name: "Statistical Analysis", domain: "Statistical", current_level: 4, current_level_label: "L4: Expert", required_level: 4, required_level_label: "L4: Expert", gap: 0, is_critical: true, organizational_priority: 5, priority_score: 0 },
    { competency_id: "comp-7", competency_name: "Sampling Techniques", domain: "Statistical", current_level: 4, current_level_label: "L4: Expert", required_level: 4, required_level_label: "L4: Expert", gap: 0, is_critical: true, organizational_priority: 4, priority_score: 0 },
    { competency_id: "comp-8", competency_name: "Data Ethics & Governance", domain: "Soft Skills", current_level: 4, current_level_label: "L4: Expert", required_level: 4, required_level_label: "L4: Expert", gap: 0, is_critical: false, organizational_priority: 3, priority_score: 0 },
    { competency_id: "comp-9", competency_name: "Technical Communication", domain: "Soft Skills", current_level: 4, current_level_label: "L4: Expert", required_level: 4, required_level_label: "L4: Expert", gap: 0, is_critical: false, organizational_priority: 3, priority_score: 0 },
    { competency_id: "comp-10", competency_name: "Data Quality Assurance", domain: "Domain", current_level: 3, current_level_label: "L3: Practitioner", required_level: 4, required_level_label: "L4: Expert", gap: 1, is_critical: true, organizational_priority: 4, priority_score: 7 },
  ],
  recommendations: [
    {
      course_id: "course-1",
      course_title: "System of National Accounts & GDP Estimation",
      provider: "iGOT Karmayogi",
      source: "iGOT Karmayogi",
      competency_id: "comp-1",
      competency_name: "National Accounts",
      current_level: 2,
      required_level: 3,
      course_target_level: 3,
      gap_score: 1,
      priority_score: 7,
      duration_minutes: 1080,
      course_level: "intermediate",
      reason: "Directly targets Critical Gap in National Accounts",
      url: "https://igotkarmayogi.gov.in",
    },
    {
      course_id: "course-2",
      course_title: "Advanced Survey Methodology & Sampling Schemes",
      provider: "TPAC",
      source: "TPAC",
      competency_id: "comp-2",
      competency_name: "Survey Design",
      current_level: 3,
      required_level: 4,
      course_target_level: 4,
      gap_score: 1,
      priority_score: 7,
      duration_minutes: 1440,
      course_level: "advanced",
      reason: "Targets Core Mandate: Survey Design",
      url: "https://mospi.gov.in/tpac",
    },
    {
      course_id: "course-3",
      course_title: "Python Data Processing & Statistical Computing",
      provider: "iGOT Karmayogi",
      source: "iGOT Karmayogi",
      competency_id: "comp-3",
      competency_name: "Python for Statistics",
      current_level: 2,
      required_level: 3,
      course_target_level: 3,
      gap_score: 1,
      priority_score: 5,
      duration_minutes: 960,
      course_level: "intermediate",
      reason: "Addresses Technical Gap in Python for Statistics",
      url: "https://igotkarmayogi.gov.in",
    },
    {
      course_id: "course-4",
      course_title: "Government Data Quality & Validation Frameworks",
      provider: "TPAC",
      source: "TPAC",
      competency_id: "comp-10",
      competency_name: "Data Quality Assurance",
      current_level: 3,
      required_level: 4,
      course_target_level: 4,
      gap_score: 1,
      priority_score: 7,
      duration_minutes: 720,
      course_level: "intermediate",
      reason: "Addresses Mission-Critical Gap in Data Quality Assurance",
      url: "https://mospi.gov.in/tpac",
    },
  ],
};

export const MOCK_ADMIN_DASHBOARD: AdminDashboardData = {
  workforce_summary: {
    total_employees: 14,
    total_departments: 3,
    total_roles: 4,
    departments: {
      "National Accounts Division (NAD)": 4,
      "National Sample Survey Office (NSSO)": 6,
      "Economic Statistics Division (ESD)": 4,
    },
    roles: {
      "Statistical Officer": 6,
      "Senior Statistical Officer": 4,
      "Data Analyst": 3,
      "System Admin": 1,
    },
  },
  gap_analytics: {
    total_gaps_count: 28,
    critical_gaps_count: 9,
    average_gap: 1.15,
    top_deficits: [
      { competency_id: "c-1", competency_name: "National Accounts", affected_employees: 8, total_gap: 9, total_priority: 56, domain: "Domain", is_critical: true },
      { competency_id: "c-2", competency_name: "Survey Design", affected_employees: 6, total_gap: 6, total_priority: 42, domain: "Statistical", is_critical: true },
      { competency_id: "c-3", competency_name: "Python for Statistics", affected_employees: 7, total_gap: 8, total_priority: 38, domain: "Technical", is_critical: false },
      { competency_id: "c-4", competency_name: "Data Quality Assurance", affected_employees: 5, total_gap: 5, total_priority: 35, domain: "Domain", is_critical: true },
    ],
  },
  proficiency_distribution: {
    "Level 1": 4,
    "Level 2": 18,
    "Level 3": 32,
    "Level 4": 45,
    "Level 5": 12,
  },
  domain_health: [
    { domain: "Statistical", average_level: 3.8, label: "L4: Expert", evaluated_count: 32 },
    { domain: "Technical", average_level: 2.9, label: "L3: Practitioner", evaluated_count: 28 },
    { domain: "Domain", average_level: 3.2, label: "L3: Practitioner", evaluated_count: 24 },
    { domain: "Soft Skills", average_level: 4.1, label: "L4: Expert", evaluated_count: 18 },
  ],
  training_effectiveness: {
    total_assessments: 28,
    completed_assessments: 22,
    reassessments_taken: 14,
    average_score: 86.5,
    competency_upgrades: 8,
  },
  content_and_ai: {
    learning_materials: 3,
    ai_questions: {
      total: 18,
      pending: 5,
      approved: 12,
      rejected: 1,
    },
  },
};

export const MOCK_ASSESSMENT: StartAssessmentResponse = {
  message: "Adaptive assessment initiated",
  assessment_id: "mock-assessment-id-1",
  assessment_type: "reassessment",
  status: "in_progress",
  total_questions: 15,
  questions: [
    {
      id: "q-1",
      question_text: "In National Sample Survey methodology, what is the primary purpose of Stratified Random Sampling?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "A",
      options: {
        A: "To ensure sub-populations are proportionately represented and reduce sampling variance",
        B: "To eliminate the need for non-response adjustments",
        C: "To replace complete enumeration census operations entirely",
        D: "To randomize surveyor allocations across regional states",
      },
      competency_id: "comp-2",
    },
    {
      id: "q-2",
      question_text: "According to the UN System of National Accounts (SNA 2008), how is Gross Value Added (GVA) at basic prices calculated?",
      question_type: "mcq",
      difficulty: "advanced",
      correct_answer: "A",
      options: {
        A: "Output at basic prices minus Intermediate Consumption at purchasers' prices",
        B: "GDP at market prices plus net subsidies on products",
        C: "Compensation of employees plus gross operating surplus minus taxes",
        D: "Gross Fixed Capital Formation minus change in inventories",
      },
      competency_id: "comp-1",
    },
    {
      id: "q-3",
      question_text: "In statistical programming with Python, which library function is best suited for vectorized data manipulation and grouped aggregations?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "A",
      options: {
        A: "pandas.DataFrame.groupby() with aggregate functions",
        B: "math.fsum() applied across standard Python lists",
        C: "json.loads() iterated over row dictionaries",
        D: "re.search() across text columns",
      },
      competency_id: "comp-3",
    },
    {
      id: "q-4",
      question_text: "Which of the following is the primary objective of the Annual Survey of Industries (ASI)?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "B",
      options: {
        A: "To collect data on agricultural crop production across all Indian states",
        B: "To compile statistics on the organized manufacturing sector",
        C: "To estimate unemployment rates in urban and rural areas",
        D: "To measure consumer price inflation for the CPI basket",
      },
      competency_id: "comp-1",
    },
    {
      id: "q-5",
      question_text: "In survey methodology, what does 'non-sampling error' primarily include?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "C",
      options: {
        A: "Errors caused by selecting a sample instead of complete enumeration",
        B: "Variability arising from the random selection of units",
        C: "Errors from data collection, processing, and non-response",
        D: "Deviations due to seasonal variation in survey responses",
      },
      competency_id: "comp-2",
    },
    {
      id: "q-6",
      question_text: "Which SQL clause is used to filter grouped results based on aggregate conditions?",
      question_type: "mcq",
      difficulty: "beginner",
      correct_answer: "C",
      options: {
        A: "WHERE",
        B: "ORDER BY",
        C: "HAVING",
        D: "LIMIT",
      },
      competency_id: "comp-5",
    },
    {
      id: "q-7",
      question_text: "What is the key principle behind the 'Official Statistics' mandate of NSO?",
      question_type: "mcq",
      difficulty: "beginner",
      correct_answer: "B",
      options: {
        A: "To publish only data that supports government policy decisions",
        B: "To provide impartial, reliable, and timely statistics for public use",
        C: "To restrict sensitive economic data to authorized ministries only",
        D: "To replace all administrative records with sample surveys",
      },
      competency_id: "comp-1",
    },
    {
      id: "q-8",
      question_text: "In metadata standards, what is the purpose of the Data Documentation Initiative (DDI) standard?",
      question_type: "mcq",
      difficulty: "advanced",
      correct_answer: "A",
      options: {
        A: "To document social science data across the research lifecycle",
        B: "To standardize satellite imagery metadata formats",
        C: "To enforce encryption protocols for confidential datasets",
        D: "To replace ISO 19115 for geospatial metadata",
      },
      competency_id: "comp-4",
    },
    {
      id: "q-9",
      question_text: "Which of the following is a key feature of the 40/60 competency combination rule?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "D",
      options: {
        A: "It gives 60% weight to historical competency and 40% to new evidence",
        B: "It ignores previous assessments and always resets to baseline",
        C: "It caps all competency upgrades at Level 3 regardless of evidence",
        D: "It weights new evidence more heavily than previous competency level",
      },
      competency_id: "comp-3",
    },
    {
      id: "q-10",
      question_text: "In the context of data quality, what does 'imputation' refer to?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "B",
      options: {
        A: "Deleting all records with missing values before analysis",
        B: "Replacing missing or inconsistent values with estimated ones",
        C: "Transforming data to logarithmic scale for normalization",
        D: "Aggregating unit-level data to regional totals",
      },
      competency_id: "comp-10",
    },
    {
      id: "q-11",
      question_text: "Which FastAPI dependency is typically used to extract the current authenticated user from a request?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "C",
      options: {
        A: "fastapi.Request",
        B: "fastapi.Response",
        C: "Depends(get_current_user)",
        D: "fastapi.Form()",
      },
      competency_id: "comp-3",
    },
    {
      id: "q-12",
      question_text: "What is the primary advantage of using pgvector in a statistical learning platform?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "A",
      options: {
        A: "It enables efficient semantic similarity search over embedded content",
        B: "It compresses PDF documents before storage",
        C: "It automates data cleaning and outlier removal",
        D: "It replaces the need for external LLM APIs entirely",
      },
      competency_id: "comp-3",
    },
    {
      id: "q-13",
      question_text: "In the role-competency framework, what does 'organizational_priority' signify?",
      question_type: "mcq",
      difficulty: "beginner",
      correct_answer: "D",
      options: {
        A: "The number of courses assigned to a specific role",
        B: "The total number of employees in a department",
        C: "The average quiz score across all assessments",
        D: "The strategic importance of a competency for organizational goals",
      },
      competency_id: "comp-6",
    },
    {
      id: "q-14",
      question_text: "Which of the following best describes the 'rebasing' operation in national accounts?",
      question_type: "mcq",
      difficulty: "advanced",
      correct_answer: "C",
      options: {
        A: "Updating survey sample frames every five years",
        B: "Replacing manual data entry with automated OCR systems",
        C: "Replacing an old base year with a new one for constant-price comparisons",
        D: "Adjusting CPI weights to reflect current household expenditure patterns",
      },
      competency_id: "comp-1",
    },
    {
      id: "q-15",
      question_text: "What is the recommended way to manage secret keys and database URLs in a FastAPI production deployment?",
      question_type: "mcq",
      difficulty: "intermediate",
      correct_answer: "B",
      options: {
        A: "Hard-code them in main.py for maximum performance",
        B: "Use environment variables or a secrets manager",
        C: "Store them in the frontend .env file",
        D: "Commit them to git so they are version controlled",
      },
      competency_id: "comp-3",
    },
  ],
};

export const MOCK_SCORE_RESULT: ScoreAssessmentResponse = {
  message: "Post-learning assessment scored successfully (40/60 Rule Applied)",
  assessment_id: "mock-assessment-id-1",
  total_questions: 3,
  correct_answers: 3,
  accuracy: 100,
  overall_score: 100,
  competency_updates: [
    {
      competency_id: "comp-2",
      competency_name: "Survey Design",
      previous_level: 3,
      evidence_level: 5,
      updated_level: 4,
      previous_gap: 1,
      new_gap: 0,
    },
    {
      competency_id: "comp-1",
      competency_name: "National Accounts",
      previous_level: 2,
      evidence_level: 4,
      updated_level: 3,
      previous_gap: 1,
      new_gap: 0,
    },
  ],
  refreshed_recommendations_count: 6,
};

export const MOCK_LEARNING_CONTENT: LearningMaterial[] = [
  {
    id: "mat-1",
    title: "Handbook of National Accounts Statistics (SNA 2008 Guidelines)",
    file_name: "SNA_2008_Handbook.pdf",
    file_type: "pdf",
    status: "indexed",
    chunk_count: 42,
    created_at: new Date().toISOString(),
  },
  {
    id: "mat-2",
    title: "NSSO Socio-Economic Survey Methodology & Design Manual",
    file_name: "NSSO_Methodology_Manual.pdf",
    file_type: "pdf",
    status: "indexed",
    chunk_count: 58,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_AI_QUESTIONS: AIGeneratedQuestionItem[] = [
  {
    id: "ai-q-1",
    learning_content_id: "mat-1",
    competency_id: "comp-1",
    question_text: "What distinguishes Basic Prices from Producer Prices in national accounting aggregates?",
    question_type: "mcq",
    options: {
      A: "Basic prices exclude taxes on products and include subsidies on products",
      B: "Basic prices include wholesale trade margins",
      C: "Basic prices are synonymous with purchaser prices",
      D: "Basic prices apply only to imported commodities",
    },
    correct_answer: "A",
    explanation: "Under SNA 2008, basic price measures the amount receivable by the producer exclusive of any tax payable and inclusive of any subsidy receivable.",
    difficulty: "advanced",
    source_chunk_ids: ["chunk-1"],
    generation_model: "gemini-1.5-flash",
    status: "approved",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "ai-q-2",
    learning_content_id: "mat-2",
    competency_id: "comp-2",
    question_text: "Why are Primary Sampling Units (PSUs) stratified geographically in large-scale rural surveys?",
    question_type: "mcq",
    options: {
      A: "To control heterogeneity and optimize fieldwork logistics across sub-districts",
      B: "To eliminate non-sampling error",
      C: "To prevent census updates from altering sample frames",
      D: "To restrict survey participation to urban areas",
    },
    correct_answer: "A",
    explanation: "Geographic stratification groups homogeneous rural villages together, enhancing precision and logistical efficiency.",
    difficulty: "intermediate",
    source_chunk_ids: ["chunk-2"],
    generation_model: "gemini-1.5-flash",
    status: "pending",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
